### LOGIN - Valid credentials
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "email": "alice@company-a.com",
  "password": "SecurePass123"
}

### LOGIN - Wrong password
POST http://localhost:7070/api/auth/login
Content-Type: application/json

{
  "email": "alice@company-a.com",
  "password": "WrongPassword"
}

### LOGOUT - Deactivate session
# Copy token from login response and paste below
POST http://localhost:7070/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBbGZyZWRvIEZlcm5hbmRleiIsInN1YiI6ImFsaWNlQGNvbXBhbnktYS5jb20iLCJleHAiOjE3NjQxNTAzMDcsImVtYWlsIjoiYWxpY2VAY29tcGFueS1hLmNvbSIsInJvbGVzIjoidXNlciJ9.D29jjcAPIHH7gEJ25D8AVN1ODa_493osyc5WSLG7h2E

### LOGOUT - Invalid token
POST http://localhost:7070/api/auth/logout
Content-Type: application/json
Authorization: Bearer invalid.token.here
